name: cmtool_mobile
description: eFootball Club Management & Analytics Mobile App (Flutter Client)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  crypto: ^3.0.3
  uuid: ^4.3.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  google_fonts: ^8.2.0
  flutter_animate: ^4.5.2
  share_plus: ^13.3.0
  path_provider: ^2.1.6
  screenshot: ^3.0.0
  supabase_flutter: ^2.16.0
  image_picker: ^1.2.3
  google_mlkit_text_recognition: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
