-- Migration: Add Player Dossier, Contact, and Compliance Verification fields to Player_Profiles
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS efootball_game_id VARCHAR(50);
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS preferred_foot VARCHAR(10) DEFAULT 'RIGHT';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS jersey_number INT DEFAULT 10;
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS system_device VARCHAR(100) DEFAULT 'REDMI NOTE 14 PRO+';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS facebook VARCHAR(255);
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10) DEFAULT 'O+';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS district VARCHAR(100) DEFAULT 'DHAKA';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT '2000-01-01';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS registrar_joined DATE DEFAULT '2026-07-26';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS contract_start DATE DEFAULT '2026-07-29';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS contract_end DATE DEFAULT '2027-01-25';

ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS facebook_link VARCHAR(100);
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS email_node VARCHAR(150);
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS phone_line VARCHAR(50);
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS node_state VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS auth_status VARCHAR(20) DEFAULT 'MEMBER';
ALTER TABLE Player_Profiles ADD COLUMN IF NOT EXISTS source_feed VARCHAR(100) DEFAULT 'CENTRAL FEDERATION';
