ALTER TABLE Match_Records
ADD COLUMN fouls INT NOT NULL DEFAULT 0,
ADD COLUMN offsides INT NOT NULL DEFAULT 0,
ADD COLUMN corners INT NOT NULL DEFAULT 0,
ADD COLUMN free_kicks INT NOT NULL DEFAULT 0,
ADD COLUMN crosses INT NOT NULL DEFAULT 0,
ADD COLUMN tackles INT NOT NULL DEFAULT 0,
ADD COLUMN saves INT NOT NULL DEFAULT 0;
