import json
import uuid
import datetime

backup_file = 'black_falcons_backup.json'
output_file = 'migrations/20260805000001_black_falcons_data.sql'

with open(backup_file, 'r') as f:
    data = json.load(f)

CLUB_ID = 'a0000000-0000-0000-0000-000000000006'

def escape_sql_string(s):
    if s is None:
        return 'NULL'
    if isinstance(s, bool):
        return 'TRUE' if s else 'FALSE'
    if isinstance(s, (int, float)):
        return str(s)
    return "'" + str(s).replace("'", "''") + "'"

with open(output_file, 'w') as out:
    out.write("-- =============================================================================\n")
    out.write("-- CMTool Database — V2 Seed Data (Black Falcons)\n")
    out.write("-- Migration: 20260805000001_black_falcons_data.sql\n")
    out.write("-- Generated by AI\n")
    out.write("-- =============================================================================\n\n")

    # 1. auth.users
    out.write("-- 1. auth.users\n")
    for u in data.get('auth_users', []):
        user_id = u['id']
        email = u['email']
        raw_meta = u.get('raw_user_meta_data', {})
        full_name = raw_meta.get('full_name', '')
        meta_json = json.dumps({
            "sub": user_id,
            "email": email,
            "email_verified": True,
            "full_name": full_name
        })
        app_meta_json = json.dumps({"provider": "email", "providers": ["email"]})
        enc_pass = '$2a$10$Q6nRi.e8VzBNQeOmra//VuO2X/Q7Jm9Hm549slcNKcLKQIkg6rAbm'  # password123
        out.write(f"INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change_token_new, email_change, reauthentication_token, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(user_id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', {escape_sql_string(email)}, '{enc_pass}', "
                  f"{escape_sql_string(u.get('email_confirmed_at'))}, {escape_sql_string(app_meta_json)}::jsonb, {escape_sql_string(meta_json)}::jsonb, '', '', '', '', '', "
                  f"{escape_sql_string(u.get('created_at'))}, {escape_sql_string(u.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password, raw_app_meta_data = EXCLUDED.raw_app_meta_data, raw_user_meta_data = EXCLUDED.raw_user_meta_data, instance_id = EXCLUDED.instance_id;\n")

    out.write("\n-- 1.1. auth.identities\n")
    for u in data.get('auth_users', []):
        user_id = u['id']
        email = u['email']
        identity_data_json = json.dumps({
            "sub": user_id,
            "email": email,
            "email_verified": True,
            "phone_verified": False
        })
        out.write(f"INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at) "
                  f"VALUES (gen_random_uuid(), {escape_sql_string(user_id)}, {escape_sql_string(user_id)}, {escape_sql_string(identity_data_json)}::jsonb, 'email', "
                  f"{escape_sql_string(u.get('created_at'))}, {escape_sql_string(u.get('created_at'))}, {escape_sql_string(u.get('updated_at'))}) "
                  f"ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data;\n")
    
    out.write("\n-- 2. public.users\n")
    # map auth users to get full_name
    auth_meta = {u['id']: u.get('raw_user_meta_data', {}).get('full_name', '') for u in data.get('auth_users', [])}
    for u in data.get('users', []):
        full_name = auth_meta.get(u['id'], '')
        out.write(f"INSERT INTO public.users (id, username, full_name, status, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(u['id'])}, {escape_sql_string(u['username'])}, {escape_sql_string(full_name)}, "
                  f"'active', {escape_sql_string(u.get('created_at'))}, {escape_sql_string(u.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")

    out.write("\n-- 3. public.clubs\n")
    for c in data.get('clubs', []):
        out.write(f"INSERT INTO public.clubs (id, name, invite_code, owner_id, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(c['id'])}, {escape_sql_string(c['name'])}, {escape_sql_string(c['invite_code'])}, "
                  f"{escape_sql_string(c.get('owner_id'))}, {escape_sql_string(c.get('created_at'))}, {escape_sql_string(c.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")

    out.write("\n-- 4. public.club_memberships\n")
    for cm in data.get('club_memberships', []):
        out.write(f"INSERT INTO public.club_memberships (club_id, player_id, role, skill_rating, form_rating, play_style, status, joined_at) "
                  f"VALUES ({escape_sql_string(cm['club_id'])}, {escape_sql_string(cm['player_id'])}, {escape_sql_string(cm['role'])}, "
                  f"{cm.get('skill_rating', 1000)}, {cm.get('form_rating', 50.0)}, {escape_sql_string(cm.get('play_style', 'Unclassified'))}, "
                  f"'active', {escape_sql_string(cm.get('joined_at'))}) "
                  f"ON CONFLICT (club_id, player_id) DO NOTHING;\n")

    out.write("\n-- 5. public.player_profiles\n")
    for pp in data.get('player_profiles', []):
        out.write(f"INSERT INTO public.player_profiles (user_id, efootball_game_id, in_game_name, preferred_foot, jersey_number, "
                  f"system_device, lifetime_matches, lifetime_wins, updated_at) "
                  f"VALUES ({escape_sql_string(pp['user_id'])}, {escape_sql_string(pp.get('efootball_game_id'))}, "
                  f"{escape_sql_string(pp.get('in_game_name', ''))}, {escape_sql_string(pp.get('preferred_foot', 'RIGHT'))}, "
                  f"{escape_sql_string(pp.get('jersey_number'))}, {escape_sql_string(pp.get('system_device'))}, "
                  f"{pp.get('lifetime_matches', 0)}, {pp.get('lifetime_wins', 0)}, {escape_sql_string(pp.get('updated_at'))}) "
                  f"ON CONFLICT (user_id) DO NOTHING;\n")

    out.write("\n-- 6. public.player_contact_info\n")
    for pp in data.get('player_profiles', []):
        out.write(f"INSERT INTO public.player_contact_info (user_id, email, phone, facebook_url, facebook_handle, blood_group, "
                  f"district, date_of_birth, updated_at) "
                  f"VALUES ({escape_sql_string(pp['user_id'])}, {escape_sql_string(pp.get('email_node'))}, "
                  f"{escape_sql_string(pp.get('phone_line'))}, {escape_sql_string(pp.get('facebook'))}, "
                  f"{escape_sql_string(pp.get('facebook_link'))}, {escape_sql_string(pp.get('blood_group'))}, "
                  f"{escape_sql_string(pp.get('district'))}, {escape_sql_string(pp.get('date_of_birth'))}, "
                  f"{escape_sql_string(pp.get('updated_at'))}) "
                  f"ON CONFLICT (user_id) DO NOTHING;\n")

    out.write("\n-- 7. public.player_compliance\n")
    for pp in data.get('player_profiles', []):
        out.write(f"INSERT INTO public.player_compliance (user_id, auth_status, node_state, source_feed, registrar_joined, "
                  f"contract_start, contract_end, updated_at) "
                  f"VALUES ({escape_sql_string(pp['user_id'])}, {escape_sql_string(pp.get('auth_status', 'MEMBER'))}, "
                  f"{escape_sql_string(pp.get('node_state', 'ACTIVE'))}, {escape_sql_string(pp.get('source_feed', 'CENTRAL FEDERATION'))}, "
                  f"{escape_sql_string(pp.get('registrar_joined'))}, {escape_sql_string(pp.get('contract_start'))}, "
                  f"{escape_sql_string(pp.get('contract_end'))}, {escape_sql_string(pp.get('updated_at'))}) "
                  f"ON CONFLICT (user_id) DO NOTHING;\n")

    out.write("\n-- 8. public.tournaments & public.tournament_participants\n")
    for t in data.get('tournaments', []):
        rc = t.get('rules_config', {})
        participant_ids = rc.pop('participant_ids', [])
        
        out.write(f"INSERT INTO public.tournaments (id, club_id, name, format_type, status, rules_config, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(t['id'])}, {escape_sql_string(t['club_id'])}, {escape_sql_string(t['name'])}, "
                  f"{escape_sql_string(t['format_type'])}, {escape_sql_string(t['status'])}, {escape_sql_string(json.dumps(rc))}::jsonb, "
                  f"{escape_sql_string(t.get('created_at'))}, {escape_sql_string(t.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")
        
        for pid in participant_ids:
            out.write(f"INSERT INTO public.tournament_participants (tournament_id, player_id) "
                      f"VALUES ({escape_sql_string(t['id'])}, {escape_sql_string(pid)}) "
                      f"ON CONFLICT (tournament_id, player_id) DO NOTHING;\n")

    out.write("\n-- 9. public.t_matches\n")
    for tm in data.get('t_matches', []):
        out.write(f"INSERT INTO public.t_matches (id, tournament_id, round_number, match_number, group_name, "
                  f"player_1_id, player_2_id, player_1_score, player_2_score, winner_id, status, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(tm['id'])}, {escape_sql_string(tm['tournament_id'])}, "
                  f"{tm.get('round_number', 1)}, {tm.get('match_number', 1)}, {escape_sql_string(tm.get('group_name'))}, "
                  f"{escape_sql_string(tm.get('player_1_id'))}, {escape_sql_string(tm.get('player_2_id'))}, "
                  f"{escape_sql_string(tm.get('player_1_score'))}, {escape_sql_string(tm.get('player_2_score'))}, "
                  f"{escape_sql_string(tm.get('winner_id'))}, {escape_sql_string(tm.get('status', 'scheduled'))}, "
                  f"{escape_sql_string(tm.get('created_at'))}, {escape_sql_string(tm.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")

    out.write("\n-- 10. public.match_records\n")
    for mr in data.get('match_records', []):
        status = mr.get('verification_status', 'approved')
        if status == 'voided':
            status = 'disputed'
        
        out.write(f"INSERT INTO public.match_records (id, club_id, player_id, opponent_id, partner_id, opponent_partner_id, "
                  f"t_match_id, match_type, result, goals_for, goals_against, possession, passes_completed, passes_attempted, "
                  f"shots_on_target, shots_total, interceptions, fouls, offsides, corners, free_kicks, crosses, tackles, saves, "
                  f"ocr_confidence, screenshot_hash, screenshot_url, verification_status, verified_by_id, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(mr['id'])}, {escape_sql_string(CLUB_ID)}, {escape_sql_string(mr['player_id'])}, "
                  f"{escape_sql_string(mr['opponent_id'])}, {escape_sql_string(mr.get('partner_id'))}, {escape_sql_string(mr.get('opponent_partner_id'))}, "
                  f"{escape_sql_string(mr.get('t_match_id'))}, {escape_sql_string(mr.get('match_type', 'friendly'))}, "
                  f"{escape_sql_string(mr['result'])}, {mr['goals_for']}, {mr['goals_against']}, {mr['possession']}, "
                  f"{mr['passes_completed']}, {mr['passes_attempted']}, {mr['shots_on_target']}, {mr['shots_total']}, "
                  f"{mr['interceptions']}, {mr.get('fouls', 0)}, {mr.get('offsides', 0)}, {mr.get('corners', 0)}, "
                  f"{mr.get('free_kicks', 0)}, {mr.get('crosses', 0)}, {mr.get('tackles', 0)}, {mr.get('saves', 0)}, "
                  f"{mr.get('ocr_confidence', 100.0)}, {escape_sql_string(mr['screenshot_hash'])}, {escape_sql_string(mr.get('screenshot_url'))}, "
                  f"{escape_sql_string(status)}, {escape_sql_string(mr.get('verified_by_id'))}, "
                  f"{escape_sql_string(mr.get('created_at'))}, {escape_sql_string(mr.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")

    out.write("\n-- 11. public.elo_history\n")
    for eh in data.get('elo_history', []):
        new_id = str(uuid.uuid4())
        out.write(f"INSERT INTO public.elo_history (id, club_id, player_id, match_record_id, rating_before, rating_after, recorded_at) "
                  f"VALUES ('{new_id}', {escape_sql_string(CLUB_ID)}, {escape_sql_string(eh['player_id'])}, "
                  f"{escape_sql_string(eh.get('match_record_id'))}, {eh['rating_before']}, {eh['rating_after']}, "
                  f"{escape_sql_string(eh.get('recorded_at'))});\n")

    out.write("\n-- 12. public.league_standings\n")
    for ls in data.get('league_standings', []):
        out.write(f"INSERT INTO public.league_standings (id, tournament_id, player_id, group_name, played, won, drawn, lost, "
                  f"goals_for, goals_against, last_processed_match_id, updated_at) "
                  f"VALUES ({escape_sql_string(ls['id'])}, {escape_sql_string(ls['tournament_id'])}, {escape_sql_string(ls['player_id'])}, "
                  f"{escape_sql_string(ls.get('group_name'))}, {ls['played']}, {ls['won']}, {ls['drawn']}, {ls['lost']}, "
                  f"{ls.get('goals_for', 0)}, {ls.get('goals_against', 0)}, {escape_sql_string(ls.get('last_processed_match_id'))}, "
                  f"{escape_sql_string(ls.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")

    out.write("\n-- 13. public.match_disputes\n")
    for md in data.get('match_disputes', []):
        out.write(f"INSERT INTO public.match_disputes (id, match_record_id, raised_by, reason, status, counter_screenshot_url, "
                  f"resolved_by, resolution_notes, resolved_at, created_at, updated_at) "
                  f"VALUES ({escape_sql_string(md['id'])}, {escape_sql_string(md['match_record_id'])}, {escape_sql_string(md['raised_by'])}, "
                  f"{escape_sql_string(md['reason'])}, {escape_sql_string(md.get('status', 'open'))}, "
                  f"{escape_sql_string(md.get('counter_screenshot_url'))}, {escape_sql_string(md.get('resolved_by'))}, "
                  f"{escape_sql_string(md.get('resolution_notes'))}, {escape_sql_string(md.get('resolved_at'))}, "
                  f"{escape_sql_string(md.get('created_at'))}, {escape_sql_string(md.get('updated_at'))}) "
                  f"ON CONFLICT (id) DO NOTHING;\n")

print("Generated SQL seed file.")
